//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moddah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Host
    {
        public long HostID { get; set; }
        public string HostName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string SSN { get; set; }
        public Nullable<long> NationalityID { get; set; }
        public string PhotoURL { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string Languages { get; set; }
        public string Gender { get; set; }
        public System.Web.HttpPostedFileBase File { get; set; }
    }
}
