//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moddah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inbox
    {
        public long InboxID { get; set; }
        public Nullable<long> FromUserID { get; set; }
        public Nullable<long> ToUserID { get; set; }
        public Nullable<System.DateTime> DateofMessage { get; set; }
        public string Subject { get; set; }
        public string BodyofMessage { get; set; }
    }
}
