//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moddah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public long ReplyID { get; set; }
        public Nullable<long> InboxID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> DateofReply { get; set; }
        public string ReplyofMesssage { get; set; }
    }
}
